name: linter
run-name: "linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  reusable-linter:
    uses: ./.github/workflows/reusable_linter.yaml
    permissions:
      contents: read
    secrets: inherit