name: reusable-linter
run-name: "reusable linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  workflow_call:
    inputs:
      actionlint:
        default: true
        required: false
        type: boolean
      shellcheck:
        default: true
        required: false
        type: boolean
      terraform-fmt:
        default: true
        required: false
        type: boolean
      terragrunt-hcl-fmt:
        default: true
        required: false
        type: boolean
      tflint:
        default: true
        required: false
        type: boolean
      trivy-config:
        default: true
        required: false
        type: boolean

  workflow_dispatch:
    inputs:
      actionlint:
        default: true
        required: false
        type: boolean
      shellcheck:
        default: true
        required: false
        type: boolean
      terraform-fmt:
        default: true
        required: false
        type: boolean
      terragrunt-hcl-fmt:
        default: true
        required: false
        type: boolean
      tflint:
        default: true
        required: false
        type: boolean
      trivy-config:
        default: true
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  # github action workflow linter
  actionlint:
    if: ${{ inputs.actionlint }}
    runs-on: ubuntu-latest
    steps:
      - uses: &checkout_action actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1, released 2025-12
      - uses: docker://rhysd/actionlint:1.7.10 # v1.7.10, released 2026-01
        with:
          args: -color

  # shell script linter
  shellcheck:
    if: ${{ inputs.shellcheck }}
    runs-on: ubuntu-latest
    steps:
      - uses: *checkout_action
      - uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0, released 2023-01
        with:
          scandir: .

  # terraform syntax linter
  terraform-fmt:
    if: ${{ inputs.terraform-fmt }}
    runs-on: ubuntu-latest
    steps:
      - uses: *checkout_action
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2, released 2024-08
        with:
          terraform_wrapper: false
      - run: terraform --version
      - run: terraform fmt -check -diff -recursive .

  # hcl syntax linter
  terragrunt-hcl-fmt:
    if: ${{ inputs.terragrunt-hcl-fmt }}
    runs-on: ubuntu-latest
    steps:
      - uses: *checkout_action
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2, released 2024-08
        with:
          terraform_wrapper: false
      - uses: gruntwork-io/terragrunt-action@95fc057922e3c3d4cc021a81a213f088f333ddef # v3.0.2, released 2025-07
        with:
          tf_path: .
          tg_version: "0.95.1" # released 2025-12
      - run: terragrunt --version
      - run: terragrunt hcl fmt --check --diff .

  # terraform linter
  tflint:
    if: ${{ inputs.tflint }}
    runs-on: ubuntu-latest
    steps:
      - uses: *checkout_action
      - uses: terraform-linters/tflint-load-config-action@5b0f6d9b68043d15c83a05d7a6dc831da411b5dd # v2.0.0, released 2024-02, checked 2026-01
        with:
          source-repo: ulfiac/common-reusables
          source-path: .tflint.hcl
          source-ref: main
      - uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33 # v6.2.1, released 2025-10
      - run: tflint --version
      - run: tflint --init
      - run: tflint --version
      - run: tflint --recursive --color

  # security scanner
  trivy-config:
    if: ${{ inputs.trivy-config }}
    runs-on: ubuntu-latest
    steps:
      - uses: *checkout_action
      - uses: aquasecurity/setup-trivy@e6c2c5e321ed9123bda567646e2f96565e34abe1 # v0.2.4, released 2025-08
      - run: trivy --version
      - run: trivy config --exit-code 1 .
