name: reusable_terraform-docs

on:
  workflow_call:
    inputs:
      find-dir:
        default: 'terraform/modules'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      find-dir:
        default: 'terraform/modules'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1, released 2025-12, checked 2026-01
      - uses: ulfiac/common-reusables/.github/actions/dump_context@main
      - uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1, released 2025-05, checked 2026-01
        with:
          args: --anchor=false
          find-dir: ${{ inputs.find-dir }}
          git-push: true
