name: reusable-linter
run-name: "reusable linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  workflow_call:
    inputs:
      actionlint:
        default: true
        required: false
        type: boolean
      shellcheck:
        default: true
        required: false
        type: boolean
      shellcheck-scandir:
        default: './scripts'
        required: false
        type: string
      terraform-fmt:
        default: true
        required: false
        type: boolean
      terraform-fmt-path:
        default: '.'
        required: false
        type: string
      tflint:
        default: true
        required: false
        type: boolean
      trivy-config:
        default: true
        required: false
        type: boolean
      trivy-config-path:
        default: '.'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      actionlint:
        default: true
        required: false
        type: boolean
      shellcheck:
        default: true
        required: false
        type: boolean
      shellcheck-scandir:
        default: './scripts'
        required: false
        type: string
      terraform-fmt:
        default: true
        required: false
        type: boolean
      terraform-fmt-path:
        default: '.'
        required: false
        type: string
      tflint:
        default: true
        required: false
        type: boolean
      trivy-config:
        default: true
        required: false
        type: boolean
      trivy-config-path:
        default: '.'
        required: false
        type: string

permissions:
  contents: read

jobs:
  # github action workflow linter
  actionlint:
    if: ${{ inputs.actionlint }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: docker://rhysd/actionlint:1.7.7
        with:
          args: -color

  # shell script linter
  shellcheck:
    if: ${{ inputs.shellcheck }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
        with:
          scandir: ${{ inputs.shellcheck-scandir }}

  # terraform syntax linter
  terraform-fmt:
    if: ${{ inputs.terraform-fmt }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false
      - run: terraform --version
      - run: terraform fmt -check -diff -recursive ${{ inputs.terraform-fmt-path }}

  # terraform linter
  tflint:
    if: ${{ inputs.tflint }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33 # v6.2.1
      - run: tflint --version
      - run: tflint --recursive

  # security scanner
  trivy-config:
    if: ${{ inputs.trivy-config }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: aquasecurity/setup-trivy@e6c2c5e321ed9123bda567646e2f96565e34abe1 # v0.2.4
      - run: trivy --version
      - run: trivy config --exit-code 1 ${{ inputs.trivy-config-path }}
